name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["OS=14.4,name=iPhone 12 Pro"]
    steps:
      - uses: actions/checkout@v2
      - name: iOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace "EGPieChart.xcworkspace" -scheme "EGPieChart" -destination "${{ matrix.destination }}"
